Calculator: node_unary Class Reference
node_unary Class Reference
#include <node_impl.hpp>
Public Member Functions
node_unary (node operand)
node operand () const
Protected Member Functions
node_unary (std::istream &stream)
double evaluate_operand () const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const =0
virtual double evaluate_node () const =0
virtual void save_node (std::ostream &stream) const =0
Private Attributes
node operand_
Detailed Description
Abstract base class for unary operators.
Definition at line 135 of file node_impl.hpp.
Constructor & Destructor Documentation
node_unary::node_unary (node operand)
Definition at line 360 of file node_impl.cpp.
: node_impl(), operand_(operand)
{}
node_unary::node_unary (std::istream & stream) [protected]
Definition at line 364 of file node_impl.cpp.
: node_impl(), operand_(stream)
{}
Member Function Documentation
node node_unary::operand () const
Definition at line 368 of file node_impl.cpp.
References operand_.
Referenced by evaluate_operand(), node_negate::print_node(), and node_negate::save_node().
{
  return operand_;
}
double node_unary::evaluate_operand () const [protected]
Definition at line 374 of file node_impl.cpp.
References node::evaluate(), and operand().
Referenced by node_negate::evaluate_node().
{
  return operand().evaluate();
}
virtual void node_unary::print_node (std::ostream & stream, int indent) const [private, pure virtual]
Implements node_impl.
Implemented in node_negate.
virtual double node_unary::evaluate_node () const [private, pure virtual]
Implements node_impl.
Implemented in node_negate.
virtual void node_unary::save_node (std::ostream & stream) const [private, pure virtual]
Implements node_impl.
Implemented in node_negate.
Member Data Documentation
node node_unary::operand_ [private]
Definition at line 147 of file node_impl.hpp.
Referenced by operand().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp