Calculator: node_negate Class Reference
node_negate Class Reference
#include <node_impl.hpp>
Public Member Functions
node_negate (node operand)
node_negate (std::istream &stream)
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const
virtual double evaluate_node () const
virtual void save_node (std::ostream &stream) const
Detailed Description
Unary negation.
Definition at line 170 of file node_impl.hpp.
Constructor & Destructor Documentation
node_negate::node_negate (node operand)
Definition at line 413 of file node_impl.cpp.
: node_unary(operand)
{}
node_negate::node_negate (std::istream & stream)
Definition at line 417 of file node_impl.cpp.
: node_unary(stream)
{}
Member Function Documentation
void node_negate::print_node (std::ostream & stream, int indent) const [private, virtual]
Implements node_unary.
Definition at line 421 of file node_impl.cpp.
References node_unary::operand(), and node::print().
{
  stream << std::setw(indent) << "" << "-\n";
  operand().print(stream, indent + 2);
}
double node_negate::evaluate_node () const [private, virtual]
Implements node_unary.
Definition at line 428 of file node_impl.cpp.
References node_unary::evaluate_operand().
{
  return -evaluate_operand();
}
void node_negate::save_node (std::ostream & stream) const [private, virtual]
Implements node_unary.
Definition at line 434 of file node_impl.cpp.
References node_unary::operand(), and node::save().
{
  stream << "negate ";
  operand().save(stream);
}
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp