Calculator: node_multiply Class Reference
node_multiply Class Reference
#include <node_impl.hpp>
Public Member Functions
node_multiply (node left, node right)
node_multiply (std::istream &stream)
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const
virtual double evaluate_node () const
virtual void save_node (std::ostream &stream) const
Detailed Description
Multiplication.
Definition at line 203 of file node_impl.hpp.
Constructor & Destructor Documentation
node_multiply::node_multiply (node left, node right)
Definition at line 505 of file node_impl.cpp.
: node_binary(left, right)
{}
node_multiply::node_multiply (std::istream & stream)
Definition at line 509 of file node_impl.cpp.
: node_binary(stream)
{}
Member Function Documentation
void node_multiply::print_node (std::ostream & stream, int indent) const [private, virtual]
Implements node_binary.
Definition at line 513 of file node_impl.cpp.
References node_binary::left(), node::print(), and node_binary::right().
{
  stream << std::setw(indent) << "" << "*\n";
  left().print(stream, indent + 2);
  right().print(stream, indent + 2);
}
double node_multiply::evaluate_node () const [private, virtual]
Implements node_binary.
Definition at line 521 of file node_impl.cpp.
References node_binary::evaluate_left(), and node_binary::evaluate_right().
{
  return evaluate_left() * evaluate_right();
}
void node_multiply::save_node (std::ostream & stream) const [private, virtual]
Implements node_binary.
Definition at line 527 of file node_impl.cpp.
References node_binary::left(), node_binary::right(), and node::save().
{
  stream << "multiply ";
  left().save(stream);
  right().save(stream);
}
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp