Calculator: node_number Class Reference
node_number Class Reference
#include <node_impl.hpp>
Public Member Functions
node_number (double value)
node_number (std::istream &stream)
double value () const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const
virtual double evaluate_node () const
virtual void save_node (std::ostream &stream) const
Private Attributes
double value_
Detailed Description
Number data type. Used for numeric literals.
Definition at line 69 of file node_impl.hpp.
Constructor & Destructor Documentation
node_number::node_number (double value)
Definition at line 137 of file node_impl.cpp.
: node_impl(), value_(value)
{}
node_number::node_number (std::istream & stream)
Definition at line 141 of file node_impl.cpp.
References value_.
: node_impl()
{
  if (not (stream >> value_))
    throw calc_error("malformed library file, cannot read number");
}
Member Function Documentation
double node_number::value () const
Definition at line 148 of file node_impl.cpp.
References value_.
Referenced by evaluate_node(), print_node(), and save_node().
{
  return value_;
}
void node_number::print_node (std::ostream & stream, int indent) const [private, virtual]
Implements node_impl.
Definition at line 154 of file node_impl.cpp.
References value().
{
  stream << std::setw(indent) << "" << value() << '\n';
}
double node_number::evaluate_node () const [private, virtual]
Implements node_impl.
Definition at line 160 of file node_impl.cpp.
References value().
{
  return value();
}
void node_number::save_node (std::ostream & stream) const [private, virtual]
Implements node_impl.
Definition at line 166 of file node_impl.cpp.
References value().
{
  stream << "number " << value() << '\n';
}
Member Data Documentation
double node_number::value_ [private]
Definition at line 79 of file node_impl.hpp.
Referenced by node_number(), and value().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp