Calculator: node_impl Class Reference
node_impl Class Reference
#include <node_impl.hpp>
Public Member Functions
node_impl ()
virtual ~node_impl ()
void print (std::ostream &stream, int indent) const
double evaluate () const
std::string to_string () const
identifier_list const & get_parameters () const
void add_ref ()
void del_ref ()
void save (std::ostream &stream) const
Static Public Member Functions
static node_impl * read_node (std::istream &stream)
Private Member Functions
node_impl (node_impl const &n)
not implemented
node_impl & operator= (node_impl const &n)
not implemented
virtual void print_node (std::ostream &stream, int indent) const =0
virtual double evaluate_node () const =0
virtual std::string evaluate_string () const
virtual
identifier_list
const & evaluate_parameters () const
virtual void save_node (std::ostream &stream) const =0
Private Attributes
std::size_t refcount_
Detailed Description
Base class for all parse tree nodes. The node classes all derive from node_impl. Each derived class overrides print_node(), for debugging and evalute_node() to evaluate the node. A few classes also override evaluate_string(), but most classes can inherit the node_impl::evaluate_string implementation, which prints the result of calling evaluate().
This class primarily manages the reference count.
Definition at line 19 of file node_impl.hpp.
Constructor & Destructor Documentation
node_impl::node_impl ()
Definition at line 11 of file node_impl.cpp.
: refcount_(1)
{}
node_impl::~node_impl () [virtual]
Definition at line 15 of file node_impl.cpp.
{}
node_impl::node_impl (node_impl const & n) [private]
not implemented
Member Function Documentation
void node_impl::print (std::ostream & stream, int indent) const
Definition at line 18 of file node_impl.cpp.
References print_node().
Referenced by node::print().
{
  print_node(stream, indent);
}
double node_impl::evaluate () const
Definition at line 24 of file node_impl.cpp.
References evaluate_node().
Referenced by node::evaluate(), and evaluate_string().
{
  return evaluate_node();
}
std::string node_impl::to_string () const
Definition at line 30 of file node_impl.cpp.
References evaluate_string().
Referenced by node::to_string().
{
  return evaluate_string();
}
identifier_list const & node_impl::get_parameters () const
Definition at line 41 of file node_impl.cpp.
References evaluate_parameters().
Referenced by node::get_parameters().
{
  return evaluate_parameters();
}
void node_impl::add_ref ()
Definition at line 36 of file node_impl.cpp.
References refcount_.
Referenced by node::node(), and node::operator=().
{
  ++refcount_;
}
void node_impl::del_ref ()
Definition at line 47 of file node_impl.cpp.
References refcount_.
Referenced by node::operator=(), and node::~node().
{
  --refcount_;
  if (refcount_ == 0)
    delete this;
}
void node_impl::save (std::ostream & stream) const
Definition at line 69 of file node_impl.cpp.
References save_node().
Referenced by node::save().
{
  save_node(stream);
}
node_impl * node_impl::read_node (std::istream & stream) [static]
Read the node type from a library file, then create the proper kind of node.
Definition at line 76 of file node_impl.cpp.
{
  std::string type;
  if (not (stream >> type))
    return 0;
  if (type == "void")
    return new node_void(stream);
  if (type == "number")
    return new node_number(stream);
  if (type == "identifier")
    return new node_identifier(stream);
  if (type == "function")
    return new node_function(stream);
  if (type == "call")
    return new node_function_call(stream);
  if (type == "negate")
    return new node_negate(stream);
  if (type == "add")
    return new node_add(stream);
  if (type == "subtract")
    return new node_subtract(stream);
  if (type == "multiply")
    return new node_multiply(stream);
  if (type == "divide")
    return new node_divide(stream);
  throw calc_error("unknown node type: " + type);
}
node_impl& node_impl::operator= (node_impl const & n) [private]
not implemented
virtual void node_impl::print_node (std::ostream & stream, int indent) const [private, pure virtual]
Implemented in node_void, node_number, node_identifier, node_function, node_function_call, node_unary, node_binary, node_negate, node_add, node_subtract, node_multiply, and node_divide.
Referenced by print().
virtual double node_impl::evaluate_node () const [private, pure virtual]
Implemented in node_void, node_number, node_identifier, node_function, node_function_call, node_unary, node_binary, node_negate, node_add, node_subtract, node_multiply, and node_divide.
Referenced by evaluate().
std::string node_impl::evaluate_string () const [private, virtual]
Reimplemented in node_void, and node_identifier.
Definition at line 54 of file node_impl.cpp.
References evaluate().
Referenced by to_string().
{
  std::ostringstream stream;
  stream << evaluate();
  return stream.str();
}
identifier_list const & node_impl::evaluate_parameters () const [private, virtual]
Reimplemented in node_function.
Definition at line 62 of file node_impl.cpp.
Referenced by get_parameters().
{
  static identifier_list const empty;
  return empty;
}
virtual void node_impl::save_node (std::ostream & stream) const [private, pure virtual]
Implemented in node_void, node_number, node_identifier, node_function, node_function_call, node_unary, node_binary, node_negate, node_add, node_subtract, node_multiply, and node_divide.
Referenced by save().
Member Data Documentation
std::size_t node_impl::refcount_ [private]
Definition at line 49 of file node_impl.hpp.
Referenced by add_ref(), and del_ref().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp