Calculator: node_add Class Reference
node_add Class Reference
#include <node_impl.hpp>
Public Member Functions
node_add (node left, node right)
node_add (std::istream &stream)
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const
virtual number evaluate_node () const
virtual void save_node (std::ostream &stream) const
Detailed Description
Addition.
Definition at line 181 of file node_impl.hpp.
Constructor & Destructor Documentation
node_add::node_add (node left, node right)
Definition at line 442 of file node_impl.cpp.
: node_binary(left, right)
{}
node_add::node_add (std::istream & stream)
Definition at line 446 of file node_impl.cpp.
: node_binary(stream)
{}
Member Function Documentation
void node_add::print_node (std::ostream & stream, int indent) const [private, virtual]
Implements node_binary.
Definition at line 450 of file node_impl.cpp.
References node_binary::left(), node::print(), and node_binary::right().
{
  stream << std::setw(indent) << "" << "+\n";
  left().print(stream, indent + 2);
  right().print(stream, indent + 2);
}
number node_add::evaluate_node () const [private, virtual]
Implements node_binary.
Definition at line 458 of file node_impl.cpp.
References node_binary::evaluate_left(), and node_binary::evaluate_right().
{
  return evaluate_left() + evaluate_right();
}
void node_add::save_node (std::ostream & stream) const [private, virtual]
Implements node_binary.
Definition at line 464 of file node_impl.cpp.
References node_binary::left(), node_binary::right(), and node::save().
{
  stream << "add ";
  left().save(stream);
  right().save(stream);
}
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp