Calculator: number_double Class Reference
number_double Class Reference
#include <number_impl.hpp>
Public Member Functions
number_double (double value)
double value () const
virtual number_impl * promote_to_void ()
Private Member Functions
virtual std::string do_to_string () const
virtual void do_save (std::ostream &stream) const
virtual bool do_equals (number_impl const &rhs) const
virtual bool do_less (number_impl const &rhs) const
virtual number_impl * do_add (number_impl const &rhs)
virtual number_impl * do_subtract (number_impl const &rhs)
virtual number_impl * do_multiply (number_impl const &rhs)
virtual number_impl * do_divide (number_impl const &rhs)
virtual number_impl * do_promote (number_impl &rhs) const
Private Attributes
double value_
Detailed Description
Represent a floating-point value. Always use double to represent floating-point values.
Definition at line 144 of file number_impl.hpp.
Constructor & Destructor Documentation
number_double::number_double (double value) [inline]
Definition at line 146 of file number_impl.hpp.
Referenced by do_add(), do_divide(), do_multiply(), and do_subtract().
: number_impl(), value_(value) {}
Member Function Documentation
double number_double::value () const [inline]
Definition at line 147 of file number_impl.hpp.
References value_.
Referenced by do_add(), do_divide(), do_equals(), do_less(), do_multiply(), do_save(), do_subtract(), and do_to_string().
{ return value_; }
number_impl * number_double::promote_to_void () [virtual]
Reimplemented from number_impl.
Definition at line 403 of file number_impl.cpp.
{
  return new number_void();
}
std::string number_double::do_to_string () const [private, virtual]
Implements number_impl.
Definition at line 348 of file number_impl.cpp.
References value().
{
  std::ostringstream stream;
  stream << value();
  return stream.str();
}
void number_double::do_save (std::ostream & stream) const [private, virtual]
Implements number_impl.
Definition at line 356 of file number_impl.cpp.
References value().
{
  stream << "double " << value() << ' ';
}
bool number_double::do_equals (number_impl const & rhs) const [private, virtual]
Implements number_impl.
Definition at line 362 of file number_impl.cpp.
References value().
{
  return value() == dynamic_cast<number_double const&>(rhs).value();
}
bool number_double::do_less (number_impl const & rhs) const [private, virtual]
Implements number_impl.
Definition at line 368 of file number_impl.cpp.
References value().
{
  return value() < dynamic_cast<number_double const&>(rhs).value();
}
number_impl * number_double::do_add (number_impl const & rhs) [private, virtual]
Implements number_impl.
Definition at line 374 of file number_impl.cpp.
References number_double(), value(), and value_.
{
  return new number_double(value_ + dynamic_cast<number_double const&>(rhs).value());
}
number_impl * number_double::do_subtract (number_impl const & rhs) [private, virtual]
Implements number_impl.
Definition at line 379 of file number_impl.cpp.
References number_double(), value(), and value_.
{
  return new number_double(value_ - dynamic_cast<number_double const&>(rhs).value());
}
number_impl * number_double::do_multiply (number_impl const & rhs) [private, virtual]
Implements number_impl.
Definition at line 384 of file number_impl.cpp.
References number_double(), value(), and value_.
{
  return new number_double(value_ * dynamic_cast<number_double const&>(rhs).value());
}
number_impl * number_double::do_divide (number_impl const & rhs) [private, virtual]
Implements number_impl.
Definition at line 389 of file number_impl.cpp.
References number_double(), value(), and value_.
{
  double right = dynamic_cast<number_double const&>(rhs).value();
  if (right == 0.0)
    throw calc_error("division by zero");
  return new number_double(value_ / right);
}
number_impl * number_double::do_promote (number_impl & rhs) const [private, virtual]
Implements number_impl.
Definition at line 397 of file number_impl.cpp.
References number_impl::promote_to_double().
{
  return rhs.promote_to_double();
}
Member Data Documentation
double number_double::value_ [private]
Definition at line 160 of file number_impl.hpp.
Referenced by do_add(), do_divide(), do_multiply(), do_subtract(), and value().
The documentation for this class was generated from the following files:
number_impl.hpp
number_impl.cpp