Calculator: node_function Class Reference
node_function Class Reference
#include <node_impl.hpp>
Public Member Functions
node_function (identifier_list const &parameters, node definition)
node_function (std::istream &stream)
identifier_list const & parameters () const
node definition () const
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const
virtual number evaluate_node () const
virtual
identifier_list
const & evaluate_parameters () const
virtual void save_node (std::ostream &stream) const
Private Attributes
identifier_list parameters_
node definition_
Detailed Description
Function definition. A function has parameters and a definition.
Definition at line 102 of file node_impl.hpp.
Constructor & Destructor Documentation
node_function::node_function (identifier_list const & parameters, node definition)
Definition at line 214 of file node_impl.cpp.
: node_impl(), parameters_(parameters), definition_(definition)
{}
node_function::node_function (std::istream & stream)
Definition at line 218 of file node_impl.cpp.
References definition_, and parameters_.
: node_impl()
{
  std::size_t size;
  if (not (stream >> size))
    throw calc_error("malformed library file, cannot read function");
  parameters_.reserve(size);
  while (size-- != 0) {
    std::string parameter;
    if (not (stream >> parameter))
      throw calc_error("malformed library file, cannot read function parameter");
    parameters_.push_back(parameter);
  }
  definition_ = node(stream);
}
Member Function Documentation
identifier_list const & node_function::parameters () const
Definition at line 234 of file node_impl.cpp.
References parameters_.
Referenced by evaluate_parameters(), print_node(), and save_node().
{
  return parameters_;
}
node node_function::definition () const
Definition at line 240 of file node_impl.cpp.
References definition_.
Referenced by evaluate_node(), print_node(), and save_node().
{
  return definition_;
}
void node_function::print_node (std::ostream & stream, int indent) const [private, virtual]
Implements node_impl.
Definition at line 257 of file node_impl.cpp.
References definition(), parameters(), node::print(), and print_identifier_list().
{
  stream << std::setw(indent) << "" << "fun\n";
  print_identifier_list(stream, parameters());
  stream << '=';
  definition().print(stream, indent + 2);
}
number node_function::evaluate_node () const [private, virtual]
Implements node_impl.
Definition at line 266 of file node_impl.cpp.
References definition(), and node::evaluate().
{
  return definition().evaluate();
}
identifier_list const & node_function::evaluate_parameters () const [private, virtual]
Reimplemented from node_impl.
Definition at line 272 of file node_impl.cpp.
References parameters().
{
  return parameters();
}
void node_function::save_node (std::ostream & stream) const [private, virtual]
Implements node_impl.
Definition at line 278 of file node_impl.cpp.
References definition(), parameters(), and node::save().
{
  stream << "function " << parameters().size() << ' ';
  std::copy(parameters().begin(), parameters().end(), std::ostream_iterator<std::string>(stream, " "));
  definition().save(stream);
}
Member Data Documentation
identifier_list node_function::parameters_ [private]
Definition at line 114 of file node_impl.hpp.
Referenced by node_function(), and parameters().
node node_function::definition_ [private]
Definition at line 115 of file node_impl.hpp.
Referenced by definition(), and node_function().
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp