Calculator: number Class Reference
number Class Reference
#include <number.hpp>
Public Member Functions
number ()
number (int x)
number (long x)
number (double x)
number (rational< long > const &x)
number (number const &n)
number & operator= (number const &n)
number (std::istream &stream)
~number ()
void save (std::ostream &stream) const
bool equals (number b)
bool less (number b)
void coerce (number &rhs)
std::string to_string () const
void print (std::ostream &stream)
number operator+ (number rhs)
number operator- (number rhs)
number operator * (number rhs)
number operator/ (number rhs)
Private Member Functions
number (number_impl *ptr)
Private Attributes
number_impl * pimpl_
Detailed Description
Number class represents a numeric value. Numbers of different types are supported, as well as conversions between types.
Definition at line 15 of file number.hpp.
Constructor & Destructor Documentation
number::number ()
Construct a void value. The calculator does not currently use void, but I can't think of a better value for a default number constructor.
Definition at line 7 of file number.cpp.
Referenced by coerce(), operator *(), operator+(), operator-(), and operator/().
: pimpl_(new number_void())
{}
number::number (int x)
Construct an int value. For the sake of simplicitly, all integers are stored as long values. This overloaded operator exists so simple uses of, say, number(0), are not ambiguous.
Parameters:
x The value of the number
Definition at line 11 of file number.cpp.
: pimpl_(new number_long(x))
{}
number::number (long x)
Construct a long value. For the sake of simplicitly, all integers are stored as long values.
Parameters:
x The value of the number
Definition at line 15 of file number.cpp.
: pimpl_(new number_long(x))
{}
number::number (double x)
Construct a floating-point value. For the sake of simplicitly, all floating-point numbers are stored as double values.
Parameters:
x The value of the number
Definition at line 23 of file number.cpp.
: pimpl_(new number_double(x))
{}
number::number (rational< long > const & x)
Construct a rational number.
Parameters:
x The value of the number
Definition at line 19 of file number.cpp.
: pimpl_(new number_rational(x))
{}
number::number (number const & n)
Copy constructor. The actual number_impl is not copied; only the reference count is incremented.
Parameters:
n The number to copy
Definition at line 27 of file number.cpp.
References number_impl::add_ref(), and pimpl_.
: pimpl_(n.pimpl_)
{
  pimpl_->add_ref();
}
number::number (std::istream & stream)
Construct a number by reading from a library file.
Definition at line 33 of file number.cpp.
: pimpl_(number_impl::read_library(stream))
{}
number::~number ()
Destructor decrements the reference count.
Definition at line 41 of file number.cpp.
References number_impl::del_ref(), and pimpl_.
{
  pimpl_->del_ref();
}
number::number (number_impl * ptr) [private]
Private constructor to create a number from a number_impl.
Parameters:
ptr Pointer to a number_impl.
Definition at line 37 of file number.cpp.
: pimpl_(pimpl)
{}
Member Function Documentation
number & number::operator= (number const & n)
Copy assignment operator. The actual number_impl is not copied; only the reference count is incremented.
Parameters:
n The number to copy
Definition at line 46 of file number.cpp.
References number_impl::add_ref(), number_impl::del_ref(), and pimpl_.
{
  that.pimpl_->add_ref();
  this->pimpl_->del_ref();
  this->pimpl_ = that.pimpl_;
  return *this;
}
void number::save (std::ostream & stream) const
Save a number to a library file.
Parameters:
stream the library stream
Definition at line 54 of file number.cpp.
References pimpl_, and number_impl::save().
Referenced by BOOST_AUTO_TEST_CASE(), and node_number::save_node().
{
  pimpl_->save(stream);
}
bool number::equals (number b)
Test for equality. Coerce this and b to the same type, then compare.
Parameters:
b the number to compare
Returns:
true if *this is numerically equal to b
Definition at line 79 of file number.cpp.
References coerce(), number_impl::equals(), and pimpl_.
Referenced by operator==().
{
  coerce(b);
  return pimpl_->equals(*b.pimpl_);
}
bool number::less (number b)
Test for less-than. Coerce this and b to the same type, then compare.
Parameters:
b the number to compare
Returns:
true if *this is numerically less than b
Definition at line 85 of file number.cpp.
References coerce(), number_impl::less(), and pimpl_.
Referenced by operator<().
{
  coerce(b);
  return pimpl_->less(*b.pimpl_);
}
void number::coerce (number & rhs)
Coerce this and rhs to the same arithmetic type. Promote the "smaller" number to the "larger" type.
number_long promotes to number_double
everything promotes to void
Parameters:
[in,out] rhs the right-hand-side operand
Definition at line 71 of file number.cpp.
References number(), pimpl_, and number_impl::promote().
Referenced by equals(), less(), operator *(), operator+(), operator-(), and operator/().
{
  // Promote that number to the type of this.
  that = number(this->pimpl_->promote(*that.pimpl_));
  // Promote this to the type of that.
  *this = number(that.pimpl_->promote(*this->pimpl_));
}
std::string number::to_string () const
Convert this number to a human-readable string.
Definition at line 60 of file number.cpp.
References pimpl_, and number_impl::to_string().
Referenced by BOOST_AUTO_TEST_CASE().
{
  return pimpl_->to_string();
}
void number::print (std::ostream & stream)
Print a number to a stream.
Parameters:
stream The output stream
Definition at line 66 of file number.cpp.
References pimpl_, and number_impl::print().
Referenced by operator<<().
{
  pimpl_->print(stream);
}
number number::operator+ (number rhs)
Addition operator. Coerce this and rhs to the same type, then add rhs and this.
Parameters:
rhs The right-hand-side operand
Returns:
*this + rhs
Definition at line 91 of file number.cpp.
References number_impl::add(), coerce(), number(), and pimpl_.
{
  coerce(rhs);
  return number(pimpl_->add(*rhs.pimpl_));
}
number number::operator- (number rhs)
Subtraction operator. Coerce this and rhs to the same type, then subtract rhs from this.
Parameters:
rhs The right-hand-side operand
Returns:
*this - rhs
Definition at line 97 of file number.cpp.
References coerce(), number(), pimpl_, and number_impl::subtract().
{
  coerce(rhs);
  return number(pimpl_->subtract(*rhs.pimpl_));
}
number number::operator * (number rhs)
Multiplication operator. Coerce this and rhs to the same type, then multiply this by rhs.
Parameters:
rhs The right-hand-side operand
Returns:
*this * rhs
Definition at line 103 of file number.cpp.
References coerce(), number_impl::multiply(), number(), and pimpl_.
{
  coerce(rhs);
  return number(pimpl_->multiply(*rhs.pimpl_));
}
number number::operator/ (number rhs)
Division operator. Coerce this and rhs to the same type, then divide this by rhs.
Parameters:
rhs The right-hand-side operand
Returns:
*this / rhs
Exceptions:
calc_error if rhs == 0.
Definition at line 109 of file number.cpp.
References coerce(), number_impl::divide(), number(), and pimpl_.
{
  coerce(rhs);
  return number(pimpl_->divide(*rhs.pimpl_));
}
Member Data Documentation
number_impl* number::pimpl_ [private]
Definition at line 129 of file number.hpp.
Referenced by coerce(), equals(), less(), number(), operator *(), operator+(), operator-(), operator/(), operator=(), print(), save(), to_string(), and ~number().
The documentation for this class was generated from the following files:
number.hpp
number.cpp