Calculator: number_impl Class Reference
number_impl Class Reference
#include <number_impl.hpp>
Public Member Functions
number_impl ()
virtual ~number_impl ()
void print (std::ostream &stream) const
std::string to_string () const
void save (std::ostream &stream) const
bool equals (number_impl const &rhs) const
bool less (number_impl const &rhs) const
number_impl * add (number_impl const &rhs)
number_impl * subtract (number_impl const &rhs)
number_impl * multiply (number_impl const &rhs)
number_impl * divide (number_impl const &rhs)
void add_ref ()
void del_ref ()
number_impl * promote (number_impl &rhs) const
virtual number_impl * promote_to_void ()
virtual number_impl * promote_to_long ()
virtual number_impl * promote_to_rational ()
virtual number_impl * promote_to_double ()
Static Public Member Functions
static number_impl * read_library (std::istream &stream)
Private Member Functions
number_impl (number_impl const &n)
not implemented
number_impl & operator= (number_impl const &n)
not implemented
virtual std::string do_to_string () const =0
virtual void do_save (std::ostream &stream) const =0
virtual bool do_equals (number_impl const &rhs) const =0
virtual bool do_less (number_impl const &rhs) const =0
virtual number_impl * do_add (number_impl const &rhs)=0
virtual number_impl * do_subtract (number_impl const &rhs)=0
virtual number_impl * do_multiply (number_impl const &rhs)=0
virtual number_impl * do_divide (number_impl const &rhs)=0
virtual number_impl * do_promote (number_impl &rhs) const =0
Private Attributes
std::size_t refcount_
Detailed Description
Definition at line 9 of file number_impl.hpp.
Constructor & Destructor Documentation
number_impl::number_impl () [inline]
Definition at line 12 of file number_impl.hpp.
: refcount_(1) {}
number_impl::~number_impl () [virtual]
Definition at line 8 of file number_impl.cpp.
{}
number_impl::number_impl (number_impl const & n) [private]
not implemented
Member Function Documentation
void number_impl::print (std::ostream & stream) const
Print in a human-readable form.
Definition at line 55 of file number_impl.cpp.
References to_string().
Referenced by number::print().
{
  stream << to_string();
}
std::string number_impl::to_string () const
Convert to a string.
Definition at line 61 of file number_impl.cpp.
References do_to_string().
Referenced by print(), and number::to_string().
{
  return do_to_string();
}
void number_impl::save (std::ostream & stream) const
Save a number to a library file.
Definition at line 23 of file number_impl.cpp.
References do_save().
Referenced by number::save().
{
  do_save(stream);
}
number_impl * number_impl::read_library (std::istream & stream) [static]
Read the number type from a library file, then create the proper kind of number.
Definition at line 29 of file number_impl.cpp.
{
  std::string type;
  if (not (stream >> type))
    throw calc_error("malformed library, missing number type");
  if (type == "void")
    return new number_void();
  if (type == "long") {
    long x;
    if (not (stream >> x))
      throw calc_error("malformed library, missing long value");
    return new number_long(x);
  }
  if (type == "double") {
    double x;
    if (not (stream >> x))
      throw calc_error("malformed library, missing double value");
    return new number_long(x);
  }
  throw calc_error("malformed library, unknown number type: " + type);
}
bool number_impl::equals (number_impl const & rhs) const
Definition at line 73 of file number_impl.cpp.
References do_equals().
Referenced by number::equals().
{
  return do_equals(rhs);
}
bool number_impl::less (number_impl const & rhs) const
Definition at line 79 of file number_impl.cpp.
References do_less().
Referenced by number::less().
{
  return do_less(rhs);
}
number_impl * number_impl::add (number_impl const & rhs)
Definition at line 85 of file number_impl.cpp.
References do_add().
Referenced by number::operator+().
{
  return do_add(rhs);
}
number_impl * number_impl::subtract (number_impl const & rhs)
Definition at line 90 of file number_impl.cpp.
References do_subtract().
Referenced by number::operator-().
{
  return do_subtract(rhs);
}
number_impl * number_impl::multiply (number_impl const & rhs)
Definition at line 95 of file number_impl.cpp.
References do_multiply().
Referenced by number::operator *().
{
  return do_multiply(rhs);
}
number_impl * number_impl::divide (number_impl const & rhs)
Definition at line 100 of file number_impl.cpp.
References do_divide().
Referenced by number::operator/().
{
  return do_divide(rhs);
}
void number_impl::add_ref ()
Definition at line 11 of file number_impl.cpp.
References refcount_.
Referenced by number_void::do_add(), number_void::do_divide(), number_void::do_multiply(), number_void::do_subtract(), number::number(), number::operator=(), promote_to_double(), promote_to_long(), promote_to_rational(), and promote_to_void().
{
  ++refcount_;
}
void number_impl::del_ref ()
Definition at line 16 of file number_impl.cpp.
References refcount_.
Referenced by number::operator=(), and number::~number().
{
  --refcount_;
  if (refcount_ == 0)
    delete this;
}
number_impl * number_impl::promote (number_impl & rhs) const
Promote rhs to match the type of this number. This function uses double-dispatch, so this number calls a virtual promote_to_*() function that notifies rhs of the desired type. If the desired type is "larger" than the type of rhs, the promote_to_*() function returns a new number_impl of the desired type. Otherwise, the function returns rhs.
Parameters:
rhs The right-hand operand of an arithmetic expression.
Definition at line 67 of file number_impl.cpp.
References do_promote().
Referenced by number::coerce().
{
  return do_promote(rhs);
}
number_impl * number_impl::promote_to_void () [virtual]
Reimplemented in number_long, number_rational, and number_double.
Definition at line 109 of file number_impl.cpp.
References add_ref().
Referenced by number_void::do_promote().
{
  add_ref();
  return this;
}
number_impl * number_impl::promote_to_long () [virtual]
Definition at line 115 of file number_impl.cpp.
References add_ref().
Referenced by number_long::do_promote().
{
  add_ref();
  return this;
}
number_impl * number_impl::promote_to_rational () [virtual]
Reimplemented in number_long.
Definition at line 121 of file number_impl.cpp.
References add_ref().
Referenced by number_rational::do_promote().
{
  add_ref();
  return this;
}
number_impl * number_impl::promote_to_double () [virtual]
Reimplemented in number_long, and number_rational.
Definition at line 127 of file number_impl.cpp.
References add_ref().
Referenced by number_double::do_promote().
{
  add_ref();
  return this;
}
number_impl& number_impl::operator= (number_impl const & n) [private]
not implemented
virtual std::string number_impl::do_to_string () const [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by to_string().
virtual void number_impl::do_save (std::ostream & stream) const [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by save().
virtual bool number_impl::do_equals (number_impl const & rhs) const [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by equals().
virtual bool number_impl::do_less (number_impl const & rhs) const [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by less().
virtual number_impl* number_impl::do_add (number_impl const & rhs) [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by add().
virtual number_impl* number_impl::do_subtract (number_impl const & rhs) [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by subtract().
virtual number_impl* number_impl::do_multiply (number_impl const & rhs) [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by multiply().
virtual number_impl* number_impl::do_divide (number_impl const & rhs) [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by divide().
virtual number_impl* number_impl::do_promote (number_impl & rhs) const [private, pure virtual]
Implemented in number_void, number_long, number_rational, and number_double.
Referenced by promote().
Member Data Documentation
std::size_t number_impl::refcount_ [private]
Definition at line 70 of file number_impl.hpp.
Referenced by add_ref(), and del_ref().
The documentation for this class was generated from the following files:
number_impl.hpp
number_impl.cpp