Calculator: node_subtract Class Reference
node_subtract Class Reference
#include <node_impl.hpp>
Public Member Functions
node_subtract (node left, node right)
node_subtract (std::istream &stream)
Private Member Functions
virtual void print_node (std::ostream &stream, int indent) const
virtual number evaluate_node () const
virtual void save_node (std::ostream &stream) const
Detailed Description
Subtraction.
Definition at line 192 of file node_impl.hpp.
Constructor & Destructor Documentation
node_subtract::node_subtract (node left, node right)
Definition at line 473 of file node_impl.cpp.
: node_binary(left, right)
{}
node_subtract::node_subtract (std::istream & stream)
Definition at line 477 of file node_impl.cpp.
: node_binary(stream)
{}
Member Function Documentation
void node_subtract::print_node (std::ostream & stream, int indent) const [private, virtual]
Implements node_binary.
Definition at line 481 of file node_impl.cpp.
References node_binary::left(), node::print(), and node_binary::right().
{
  stream << std::setw(indent) << "" << "-\n";
  left().print(stream, indent + 2);
  right().print(stream, indent + 2);
}
number node_subtract::evaluate_node () const [private, virtual]
Implements node_binary.
Definition at line 489 of file node_impl.cpp.
References node_binary::evaluate_left(), and node_binary::evaluate_right().
{
  return evaluate_left() - evaluate_right();
}
void node_subtract::save_node (std::ostream & stream) const [private, virtual]
Implements node_binary.
Definition at line 495 of file node_impl.cpp.
References node_binary::left(), node_binary::right(), and node::save().
{
  stream << "subtract ";
  left().save(stream);
  right().save(stream);
}
The documentation for this class was generated from the following files:
node_impl.hpp
node_impl.cpp