Calculator: variables.cpp File Reference
variables.cpp File Reference
#include <fstream>
#include <istream>
#include <limits>
#include <map>
#include <ostream>
#include "calc_error.hpp"
#include "node.hpp"
#include "variables.hpp"
Functions
bool find_symbol (std::string const &name, node &value)
node get_variable (std::string const &name)
void set_variable (std::string const &name, node value)
node get_function (std::string const &name)
void set_function (std::string const &name, node value)
void save_library (std::string const &filename)
void load_library (std::string const &filename)
Variables
symbol_table variables
std::vector
< symbol_table const * > symbol_tables
initializer init
Function Documentation
bool find_symbol (std::string const & name, node & value)
Definition at line 36 of file variables.cpp.
References symbol_tables.
Referenced by get_function(), and get_variable().
{
  for (std::vector<symbol_table const*>::reverse_iterator iter(symbol_tables.rbegin()); iter != symbol_tables.rend(); ++iter) {
    symbol_table const& table( **iter );
    symbol_table::const_iterator entry = table.find(name);
    if (entry != table.end()) {
      value = entry->second;
      return true;
    }
  }
  return false;
}
node get_function (std::string const & name)
Get the definition of a function.
Parameters:
name The function name
Returns:
The definition of function named name
Exceptions:
no_such_function if the function is not defined
Definition at line 65 of file variables.cpp.
Referenced by node_function_call::evaluate_node().
{
  node result;
  if (not find_symbol(name, result))
    throw no_such_function(name);
  else
    return result;
}
node get_variable (std::string const & name)
Get the value of a variable.
Parameters:
name The variable name
Returns:
The value of variable name or node() if the variable is undefined.
Definition at line 49 of file variables.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and node_identifier::evaluate_node().
{
  node result;
  if (not find_symbol(name, result))
    return node();
  else if (result.get_parameters().empty())
    return result;
  else
    throw function_error(name, result.get_parameters().size(), 0);
}
void load_library (std::string const & filename)
Load variable and function definitions from a file. Definitions in the file overwrite existing definitions with the same name.
Parameters:
filename The file name
Exceptions:
calc_error for I/O errors
Definition at line 99 of file variables.cpp.
Referenced by parser::get_statement().
{
  std::ifstream stream(filename.c_str());
  if (not stream)
    throw file_error(filename);
  std::string token;
  if (not std::getline(stream, token))
    throw calc_error(filename + ": is empty");
  if (token != ":library:")
    throw calc_error(filename + ": is not a calculator library file");
  while (stream >> token) {
    if (token == "*")
      return;
    else
      set_variable(token, node(stream));
  }
}
void save_library (std::string const & filename)
Save all variable and function definitions to a file. The file is a simple text file, so you can examine it in any text editor.
Parameters:
filename The name of the file.
Exceptions:
calc_error if the file cannot be created
Definition at line 79 of file variables.cpp.
Referenced by parser::get_statement().
{
  std::ofstream stream(filename.c_str());
  if (not stream)
    throw file_error(filename);
  // Be sure to save numbers with maximum precision.
  stream.precision(std::numeric_limits<double>::digits10);
  stream << ":library:\n";
  for (symbol_table::iterator symbol(variables.begin()); symbol != variables.end(); ++symbol) {
    stream << symbol->first << ' ';
    symbol->second.save(stream);
    if (stream.fail())
      throw file_error(filename);
  }
  stream << "*\n";
  stream.close();
  if (stream.fail())
    throw file_error(filename);
}
void set_function (std::string const & name, node definition)
Set the definition of a function.
Parameters:
name The function name
definition The function definition
Definition at line 74 of file variables.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and parser::get_statement().
{
  set_variable(name, value);
}
void set_variable (std::string const & name, node value)
Set the value of a variable.
Parameters:
name The variable name
value The value. if the variable is already defined, changes its value.
Definition at line 60 of file variables.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), load_library(), and set_function().
{
  variables[name] = value;
}
Variable Documentation
initializer init [static]
Definition at line 23 of file variables.cpp.
std::vector<symbol_table const*> symbol_tables [static]
Definition at line 13 of file variables.cpp.
Referenced by find_symbol(), set_symbol_table::set_symbol_table(), and set_symbol_table::~set_symbol_table().
symbol_table variables [static]
Definition at line 12 of file variables.cpp.
Referenced by save_library(), and set_variable().