Exploring C++ - Final Forms of Key Examples: fakemake.cpp File Reference
fakemake.cpp File Reference
#include <ctime>
#include <iostream>
#include <istream>
#include <ostream>
#include <sstream>
#include <string>
#include <utility>
#include "artifact.hpp"
#include "depgraph.hpp"
#include "variables.hpp"
Functions
artifact & lookup_artifact (std::string const &name)
Lookup an artifact in the parse map.
void parse_graph (std::istream &in, dependency_graph &graph)
int main ()
Variables
std::map
< std::string,
artifact > artifacts
Store all artifacts here as they are read.
Detailed Description
Definition in file fakemake.cpp.
Function Documentation
void parse_graph (std::istream & in, dependency_graph & graph)
Parse the fakemakefile, building a dependency graph.
Parameters:
[in] in The input stream
[out] graph The dependency graph to build
Definition at line 34 of file fakemake.cpp.
References artifacts, artifact::expand(), expand(), global_variables, lookup_artifact(), dependency_graph::store_dependency(), and artifact::store_variable().
Referenced by main().
Variable Documentation
std::map<std::string, artifact> artifacts
Store all artifacts here as they are read.
Listing 60-9. Rewriting the Program to Use the New artifact Value Class
Definition at line 16 of file fakemake.cpp.
Referenced by lookup_artifact(), and parse_graph().